name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Deploy to Render
        uses: render-examples/render-deploy@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_name: "your-service-name"
